version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    commit-message:
      include: scope
      prefix: ":arrow_up: "
    schedule:
      timezone: "America/Chicago"
      time: "22:00"
      interval: daily
